### PR TITLE
Djs dict updates

### PR DESCRIPTION
**Pull request by dstorer**
Just a few updates to the dictionary.

### CODE REVIEW

**Comment by dstorer** [comment]
@nicelmh @PyxieLouStar can one of you review this branch? I just realized it's been sitting for a while and may as well be merged in.

**Comment by PyxieLouStar** [comment]
Looks like `no_png` is now in the dictionary twice

**Comment by dstorer** [comment]
@PyxieLouStar thanks, I hadn't noticed that when I did the rebase. It should be fixed now!

**Review by PyxieLouStar — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
